### ISSUE TITLE
Android app closes after every keystroke when entering server address

### ISSUE THREAD

**Issue by jakendrick3** [MohamedBassem/hoarder-app#114]
Pretty much title. Went into a browser and copied the link I needed but even then deleting the /signin end of the URL took a hot second with the keyboard closing every time, lol.

**Comment by MohamedBassem** [comment]
Hi, this is supposedly fixed in version 1.5. Can you check if there's an app update and let me know if the problem still exists?

**Comment by jakendrick3** [comment]
Oh, that fixed it. Sorry, my bad!!!

**Comment by MohamedBassem** [comment]
Perfect, no worries!
