### ISSUE TITLE
INFERENCE_LANG not working?

### ISSUE THREAD

**Issue by mikkelnl** [MohamedBassem/hoarder-app#120]
Hi!

I tried setting INFERENCE_LANG to 'dutch', but this doesn't seem to work; tags are still generated in English.

Am I doing something wrong maybe?

**Comment by MohamedBassem** [comment]
Hi, did you re-run `docker compose up` after adding this setting?

**Comment by mikkelnl** [comment]
> Hi, did you re-run `docker compose up` after adding this setting?

Hmm, I'm using the Synology docker GUI, there I stop the container, add the setting, restart te container... not sure if that is the same as docker compose up.......

**Comment by mikkelnl** [comment]
I tried Portainer; there is a recreate option. That didn't fix it ;-) 

So far, with other containers I run via the Synology GUI, I've added and edited variables a few times, which would work after the container is restarted... My guess is Hoarder doesn't seem to recognize the variable... is 'dutch' a valid value?

**Comment by mikkelnl** [comment]
Hmm, to the WEB container, I'm guessing it should be added to one of the others? :)

**Comment by MohamedBassem** [comment]
Yes, this should only be added to the workers container.

**Comment by mikkelnl** [comment]
Thanks, that makes perfect sense, sorry to have used your time!
