### ISSUE TITLE
Make Redis database number configurable

### ISSUE THREAD

**Issue by jandillmann** [MohamedBassem/hoarder-app#13]
Redis supports 16 different databases, numbered from `0` to `15`. By default, clients connect to database `0`.

If the database number was configurable I could use my already running Redis instance, instead of spinning up a new one.

It seems like this project uses BullMQ, which itself uses ioredis. The configuration option `db` is the "Database index to use.".

More information: https://github.com/redis/ioredis/blob/v4/API.md#new-redisport-host-options

**Comment by MohamedBassem** [comment]
Makes sense, will send a quick PR soon :)

**Comment by jandillmann** [comment]
Thank you 🤩

**Comment by MohamedBassem** [comment]
You're welcome! It'll be available in the next release happening very soon (probably later today).
