### ISSUE TITLE
[Bug] Items created in the same second may not be shown in the bookmark grid due to pagination

### ISSUE THREAD

**Issue by MohamedBassem** [MohamedBassem/hoarder-app#140]
When we're paginating using `createdAt` only, items created in the same second can result in duplicates or missing items.

**Comment by kamtschatka** [comment]
I ran into this issue also just now. Of course this happens a lot if you import a lot of bookmarks using the cli (or in my case the PR to allow importing bookmarks via the UI)

I noticed that it is an easy fix in schema.ts by changing `timestamp` to `timestamp_ms` in the createdAtField.
I tried running the database migrations (https://docs.hoarder.app/Development/database), but it only adds 
`CREATE INDEX `bookmarkLinks_url_idx` ON `bookmarkLinks` (`url`);`

I was hoping that would also create a migration of the existing timestamps, but seems like it doesn't.

**Comment by MohamedBassem** [comment]
@kamtschatka Changing the mode of the column is a software layer thing. You'll have to create an empty migration with `pnpm drizzle-kit generate:sqlite --custom` and write some SQL to multiple all the `createdAt` columns by 1000. However, using milliseconds makes the chances of the problem happening lower but it doesn't really solve the problem. The proper fix is to paginate both on `createdAt` and the `id`. But we'll need to be careful if we're to do that in a backward compatible way.

As for what you got when you generated a migration, that's actually my fault. I apparently forgot to create a migration when I implemented the URL dedups :) Will get that fixed.

**Comment by MohamedBassem** [comment]
Pushed https://github.com/MohamedBassem/hoarder-app/commit/c9dc23f43e0d87453b74105a8ffc81ce9f4bd98a to fix the dangling migration problem.

**Comment by MohamedBassem** [comment]
I think fixing the pagination shouldn't be hard. I'll prioritize it specially in the context of your PR to support importing from the UI.
