### ISSUE TITLE
Take full page screenshots

### ISSUE THREAD

**Issue by kamtschatka** [MohamedBassem/hoarder-app#143]
Taking a screenshot of the page would be much better if it would take a full page screenshot.
If I am not mistaken it should only require a change in [this line](https://github.com/MohamedBassem/hoarder-app/blob/edf5fdbec67278e81c3538a553d567ff0a37d798/apps/workers/crawlerWorker.ts#L230) to add ["fullpage: true" ](https://www.webshare.io/academy-article/puppeteer-screenshot#how-to-screenshot-the-full-page)

**Comment by kamtschatka** [comment]
Yeah I tried it out and it works fine, but I can't figure out how to make the screenshot show up correctly.
Tried all kinds of things with ScreenshotSection.tsx, but the screenshot stays like this:
![image](https://github.com/MohamedBassem/hoarder-app/assets/22147234/e33cfe75-d819-424b-8e30-65c129b165c5)

If I remove the "height: 100%" style from the create image tag it looks fine, but I don't understand how that works with the "Image" tag from next:
![image](https://github.com/MohamedBassem/hoarder-app/assets/22147234/3a347208-ddf6-4625-9d78-bff1bdc5e33f)

**Comment by scubanarc** [comment]
I didn't look at the source, but it seems like some sort of height-limited div with "overflow:hidden" might to do the trick.

**Comment by MohamedBassem** [comment]
Yeah, dealing with the `Image` tag of next can be very annoying :) I'll check it over the weekend.

I think also I'll also make this behavior configurable. Screenshots can take a ton of disk space specially with that size and not everyone finds them useful.

**Comment by MohamedBassem** [comment]
Nice! will check it out!

By configurable, I mean with an env variable. All config knobs are here: https://github.com/MohamedBassem/hoarder-app/blob/main/packages/shared/config.ts and you'll find this `serverConfig` option used a lot in the `crawlerWorker.ts` already. And if it's not too much, I'd be grateful if you add the new env variable to the docs here as well https://github.com/MohamedBassem/hoarder-app/blob/main/docs/docs/03-configuration.md :) I think we can name it `CRAWLER_FULL_PAGE_SCREENSHOT`.

**Comment by MohamedBassem** [comment]
@kamtschatka implemented in #148!
