### ISSUE TITLE
Odd Chrome extension behavior

### ISSUE THREAD

**Issue by jegwastaken** [MohamedBassem/hoarder-app#149]
Clicking the extension icon when on an already saved page creates a duplicate bookmark. Is this by design? Shouldn't I be able to edit the existing one instead?

P.S. Awesome app :)

**Comment by MohamedBassem** [comment]
Already landed a change to prevent that from happening. It'll be available in the next release :)

**Comment by jegwastaken** [comment]
Thank you.

**Comment by MohamedBassem** [comment]
For reference: https://github.com/MohamedBassem/hoarder-app/commit/32b5a025568dcc5788a8a2afc19bf07264e01a63

Closing the issue for now.
