### ISSUE TITLE
Questions about search questions and multi -language support

### ISSUE THREAD

**Issue by Swim0o0** [MohamedBassem/hoarder-app#157]
**Description**：
1. Many of the bookmarks I added are Chinese (of course, there are pure English bookmarks). I don't know if it is because of language. The search function of the Hoarder cannot be used (even searching for pure English bookmark content).This is what I have not encountered in Demo.
2. When searching in DEMO, enter the keyword to find the bookmark you want. After deleting the keywords according to `Backspace`, the Hoarder will automatically return to the main interface.But after I deployed it through Docker, I found that I could not achieve this effect.

**Gif**：
![a gif show bug](https://github.com/MohamedBassem/hoarder-app/assets/89305852/0b29b9b5-c2e3-476f-b7b8-dc59a3cb1a3d)

**Comment by MohamedBassem** [comment]
Hi, this is not normal and I don't think it's language related. You seem to have some problem with your meilisearch setup. Can you share the logs of you worker container?

**Comment by Swim0o0** [comment]
> Hi, this is not normal and I don't think it's language related. You seem to have some problem with your meilisearch setup. Can you share the logs of your worker container? And maybe also the logs of the web container.

I was studying this problem in the past two days, and I initially believed that it was the problem of the meilisearch version, because in the [issue](https://github.com/meilisearch/meilisearch/issues/4300) of Meilisearch, someone encountered the same problem as the logs I provided. [This](https://github.com/meilisearch/meilisearch/issues/4300#issuecomment-1980776009) is a solution provided by a contributor of Meilisearch.
[workers log.txt](https://github.com/MohamedBassem/hoarder-app/files/15367488/workers.log.txt)

**Comment by Swim0o0** [comment]
I deleted the Docker volume, Docker network, Docker mirror image, etc., and then re -deployed to find that the search function can be used normally.😄

**Comment by MohamedBassem** [comment]
Perfect. I'm glad you managed to get it working!
