### ISSUE TITLE
Consider using a named .env file

### ISSUE THREAD

**Issue by olliejudge** [MohamedBassem/hoarder-app#16]
MacOS doesn't like empty named .env files, so when running the docker script I needed to give a full name and modify the compose file to reflect a hoarder.env file

**Comment by MohamedBassem** [comment]
That's weird, seems to be working fine for me. What kind of errors are you getting?

<img width="611" alt="Screenshot 2024-03-27 at 11 04 09 AM" src="https://github.com/MohamedBassem/hoarder-app/assets/2418637/f4b12654-3397-4fac-84ce-d48e3d5b48e8">

**Comment by MohamedBassem** [comment]
Please reopen if you're still facing an issue
