### ISSUE TITLE
[Feature request] Alphabetical sorting of tag select dropdown

### ISSUE THREAD

**Issue by lilacpixel** [MohamedBassem/hoarder-app#171]
When adding new tags for a bookmark in the preview modal, the tag select dropdown shows existing tags in the order they were created.

![Screenshot 2024-05-19 at 11 00 11 AM](https://github.com/MohamedBassem/hoarder-app/assets/44416326/d497e7c7-6259-4ca3-b5e8-920ac77025fd)

An alphabetical sort might make it a little easier to scroll through and see what tags already exist. I see that #80 was closed out yesterday, but that sorting only covers the tags page itself. Would a default alphabetical sort on the database level be useful to anyone else? I'm still rifling through code and trying to make sense of the new stack, but if there's a need and someone else wants to take a crack at it, I'd be super grateful 😁

**Comment by MohamedBassem** [comment]
hmmm, I'm surprised that I didn't end up sorting that list. The tag selector in the browser extension is sorted, so the one in preview should be sorted as well. I don't think we need to do it on the database level, just sorting it in the TagSelector of the web app should suffice. Let me send a quick commit now.

**Comment by lilacpixel** [comment]
From feature request to code push in less than 15 minutes--that's got to be some kind of record 😉 Thank you so much!
