### ISSUE TITLE
Server address with / breaks extension configuration

### ISSUE THREAD

**Issue by mape** [MohamedBassem/hoarder-app#18]
When you use a Server Address ending with a slash (`https://sub.domain.tld/`) the extension shows **Failed to fetch**.

Dev tools logs:

    Access to fetch at 'https://sub.domain.tld//api/trpc/apiKeys.exchange?batch=1' from origin 'chrome-extension://kgcjekpmcjjogibpjebkhaanilehneje' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

Removing the slash fixes the issue.

**Comment by MohamedBassem** [comment]
Thanks for the report! That's indeed a bug, will send a quick PR to fix it :)
