### ISSUE TITLE
Keyboard shortcut for saving new bookmark is not cross platfrom

### ISSUE THREAD

**Issue by joshuapeterson** [MohamedBassem/hoarder-app#24]
If I paste a bookmark into the Upper Left box the button on the bottom changes to "Press ⌘+Enter to Save".  This is on a Windows machine.  I do not have a command key, and no combination of Ctrl or Alt seems to work.  I can still press the button with the mouse.

**Comment by MohamedBassem** [comment]
It was configured to use the `Meta` key, which on windows is I think the "Windows" key?
Anyways, I submitted a fix to allow also `Ctrl + Enter` :)
