### ISSUE TITLE
Unable to manually edit title

### ISSUE THREAD

**Issue by fauxvo** [MohamedBassem/hoarder-app#27]
Great repo BTW!  Thank you!

Once I've added my bookmark, I'd like to manually edit the title of the item.  Yes, the scraper does grab the title text from the metadata but I'd like to change it myself.

Is this possible?

Also, is it possible to import my list of bookmarks from Chrome or another browser?

**Comment by MohamedBassem** [comment]
Currently, editing the title is not possible. It's, however, something that should be implemented. Thanks for requesting it!

As for importing stuff from chrome, you can follow https://github.com/MohamedBassem/hoarder-app/issues/7 for the progress.

**Comment by yannduran** [comment]
I assume that the PR installed a "useable" `edit Link` button to the actions behind  the `...` button.

Forgive me, I'm not a web developer, I know enough of Javascript to know that I need to know more about Javascript. I know nothing about using Vue.

I have a bunch of bookmarks added, but while some provide perfect titles, others just use its, sometimes, weird filename. I was hoping that I'd be able to simply change that to the title of the article. But everything that I clicked, there was never a `Edit title` option.

Am I just missing something obvious? Or am I wanting to use it incorrectly? Or have I not read something that I should have read?

TIA if you're, or anyone is, able to shed some light on my plight.
