### ISSUE TITLE
Dark mode support in Firefox extension

### ISSUE THREAD

**Issue by vercas** [MohamedBassem/hoarder-app#30]
This is what it currently looks like when bookmarking a page:
<img width="393" alt="Screenshot 2024-03-27 at 17 22 09" src="https://github.com/MohamedBassem/hoarder-app/assets/1823741/f35a4190-2d19-4294-b9e5-196516873dac">

**Comment by JFPCreations** [comment]
+1
I was about to post the same but for chrome extension in Brave. ;) 
Because of dark theme the popup is looking weird.

**Comment by MohamedBassem** [comment]
Thanks for the report, I think it looks slightly nicer now. Will be available in the next extension release.

<img width="384" alt="Screenshot 2024-03-27 at 5 58 03 PM" src="https://github.com/MohamedBassem/hoarder-app/assets/2418637/1b2402e8-c4aa-4eb7-9c0d-de3271f0b0f8">

**Comment by JFPCreations** [comment]
Thank you for this fast work. Did you or can you add a white icon the the dark theme? 
![image](https://github.com/MohamedBassem/hoarder-app/assets/10256543/c7f2800b-b326-4aad-a3c0-f229c0bd46b0)

**Comment by MohamedBassem** [comment]
I don't think I can customize the icon based on wether it's light mode or dark mode. I checked and chrome developer's guide suggestion is to add a subtle white glow around the logo to make it visible in dark mode. Let me do that.

**Comment by vercas** [comment]
This extension does it in Firefox: https://github.com/Mika-/torrent-control

**Comment by JFPCreations** [comment]
I think you have upgraded the extension. 

It is viewable now.

![image](https://github.com/MohamedBassem/hoarder-app/assets/10256543/88252fe4-acd2-47ec-85c2-191f4b10e6d8)

Thank you.
