### ISSUE TITLE
Android APP.

### ISSUE THREAD

**Issue by JFPCreations** [MohamedBassem/hoarder-app#31]
Really like your tool.

I was able to add ollama for AI work, but I'm a bit lost for Android.

How to use the bookmarking tool/app in android?

Thank you.

**Comment by MohamedBassem** [comment]
The android app is coming soon. You can follow its progress here (https://github.com/MohamedBassem/hoarder-app/issues/6).

**Comment by MohamedBassem** [comment]
Closing this given that it's tracked in #6
