### ISSUE TITLE
Asset too Big

### ISSUE THREAD

**Issue by runinit** [MohamedBassem/hoarder-app#33]
Testing out this app on my homelab. Testing uploads of various images and i ran into an issue with a 17MB PNG File.

![image](https://github.com/MohamedBassem/hoarder-app/assets/1857485/b9a7d90e-7e50-40ac-b9dd-b132aea558b9)

**Comment by MohamedBassem** [comment]
There's currently a limit of 4MB per asset. I think I can make this configurable as an environment variable.
