### ISSUE TITLE
Request for HTTP and SOCKS5 Proxy Support

### ISSUE THREAD

**Issue by daydaya** [MohamedBassem/hoarder-app#38]
Hi,

**Could you add support for HTTP and SOCKS5 proxies?** 

Many users, including myself, need proxies to access sites like Google and Facebook due to local internet restrictions. 
This feature would help a lot.

Thanks,

**Comment by MohamedBassem** [comment]
I **think** this might be possible right now by passing extra arguments to the chrome docker container. This is where the chrome args are passed: https://github.com/MohamedBassem/hoarder-app/blob/main/docker/docker-compose.yml#L24

You might try to add some of the proxy flags documented in chromium here: https://www.chromium.org/developers/design-documents/network-settings/

**Comment by MohamedBassem** [comment]
I'll mark this as closed. If you tried it and it didn't work, please reopen.

**Comment by daydaya** [comment]
Thank you very much！

Here is an example of my new startup parameters, I hope it is useful to others:
`- --proxy-server="http=192.168.1.129:7890;https=192.168.1.129:7890"`
`- --proxy-bypass-list="*.local;127.0.0.1;localhost;"`

**Comment by czy1996** [comment]
> `- --proxy-server="http=192.168.1.129:7890;https=192.168.1.129:7890"`
> `- --proxy-bypass-list="*.local;127.0.0.1;localhost"`

Sorry to bother you, I am new to karakeep, and the parameters above seems not working in latest version(0.23.1), have u encontered similar issues and how do you solve it ?

**Comment by maidou-00** [comment]
> > `- --proxy-server="http=192.168.1.129:7890;https=192.168.1.129:7890"`
> > `- --proxy-bypass-list="*.local;127.0.0.1;localhost"`
> 
> Sorry to bother you, I am new to karakeep, and the parameters above seems not working in latest version(0.23.1), have u encontered similar issues and how do you solve it ?

same here, I just can't get it to work. The only solution I've found so far is to enable proxy on my router.

**Comment by nickhelion** [comment]
> > > `- --proxy-server="http=192.168.1.129:7890;https=192.168.1.129:7890"`
> > > `- --proxy-bypass-list="*.local;127.0.0.1;localhost"`
> > 
> > 
> > Sorry to bother you, I am new to karakeep, and the parameters above seems not working in latest version(0.23.1), have u encontered similar issues and how do you solve it ?
> 
> same here, I just can't get it to work. The only solution I've found so far is to enable proxy on my router.


I resolved my issue via #1265 , may not work for you but worth a try
