### ISSUE TITLE
MeiliSearchApiError: The Authorization header is missing. It must use the bearer authorization method.

### ISSUE THREAD

**Issue by Aerics84** [MohamedBassem/hoarder-app#44]
I have this error inside the Hoarder-WORKERS container:
**openai job failed: MeiliSearchApiError: The Authorization header is missing. It must use the bearer authorization method.**

And i get this error inside the Hoarder-MEILI container:
```
MeiliSearchApiError: The Authorization header is missing. It must use the bearer authorization method.
    at /app/apps/web/.next/server/chunks/673.js:4817:1188
    ... 2 lines matching cause stack trace ...
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  [cause]: l [MeiliSearchApiError]: The Authorization header is missing. It must use the bearer authorization method.
      at /app/apps/web/.next/server/chunks/673.js:4817:1188
      at Generator.next (<anonymous>)
      at s (/app/apps/web/.next/server/chunks/673.js:4815:69399)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 'missing_authorization_header',
    type: 'auth',
    link: 'https://docs.meilisearch.com/errors#missing_authorization_header',
    httpStatus: 401
  }
}
```

**Comment by MohamedBassem** [comment]
Did you setup the required env variables here (https://docs.hoarder.app/installation#3-populate-the-environment-variables)?
 Seems like you're probably missing the `MEILI_MASTER_KEY` var.

**Comment by Aerics84** [comment]
`version: "3.9"
services:
  web:
    image: ghcr.io/mohamedbassem/hoarder-web:latest
    container_name: Hoarder-WEB
    restart: on-failure:5
    volumes:
      - /volume1/docker/hoarder/data:/data:rw
    ports:
      - 8096:3000
    networks:
      - hoarder      
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      DATA_DIR: /data
      NEXTAUTH_SECRET: SaTLKAn^Xe*j2&35@m!Ln!AgK3uXXXXX
      
  redis:
    image: redis:7.2-alpine
    container_name: Hoarder-REDIS
    restart: on-failure:5
    volumes:
      - /volume1/docker/hoarder/redis:/data:rw
    networks:
      - hoarder      
      
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:100
    container_name: Hoarder-CHROME
    restart: on-failure:5
    networks:
      - hoarder    
    command:
      - --no-sandbox
      - --disable-gpu
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      
  meilisearch:
    image: getmeili/meilisearch:v1.6
    container_name: Hoarder-MEILI
    restart: unless-stopped
    volumes:
      - /volume1/docker/hoarder/meili:/meili_data:rw
    networks:
      - hoarder      
    environment:
     MEILI_MASTER_KEY: q3D6WN&Sqtz^tu*%KK2GaAcnt9fXXXXX
     
  workers:
    image: ghcr.io/mohamedbassem/hoarder-workers:latest
    container_name: Hoarder-WORKERS
    restart: on-failure:5
    volumes:
      - /volume1/docker/hoarder/data:/data:rw
    networks:
      - hoarder      
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      NEXTAUTH_SECRET: SaTLKAn^Xe*j2&35@m!Ln!AgK3uXXXXX
      DATA_DIR: /data
      OPENAI_API_KEY: sk-XXXXX
    depends_on:
      web:
        condition: service_started

networks:
  hoarder:
    external: true`

**Comment by MohamedBassem** [comment]
MEILI_MASTER_KEY needs to be set up on the `web` and `workers` containers as well

**Comment by Aerics84** [comment]
Thats it. Thanks.
