### ISSUE TITLE
IOS App, non standard port ( Network Request Failed )

### ISSUE THREAD

**Issue by vikramwalia** [MohamedBassem/hoarder-app#48]
![IMG_3681](https://github.com/MohamedBassem/hoarder-app/assets/46508515/967ecf39-c422-4ddd-8e1d-00c1698c32f7)

Erroring out on a nonstandard port.

**Comment by MohamedBassem** [comment]
Custom ports should work just fine. This might be related to a bug that I fixed in 2cd2f92e9e0c82eaa5f21fe0c30e20ebea7aba24 (released as version 1.3.1, but it's still pending apple's review). Can you try force closing the app and starting it again? The bug was that sometimes updating the address doesn't get correctly reflected in the trpc client without a full re-render for the app.

**Comment by vikramwalia** [comment]
Thank you, I had to restart twice ( same error ) and on third try got it to work. I will wait for 1.3.1 to come through and test again. Much appreciated.

**Comment by MohamedBassem** [comment]
I'll close this for now and we can re-open it if `1.3.1` doesn't solve the issue.

**Comment by dodgog** [comment]
Hi! Getting the same exact issue on the latest ios app here. Using http://ipv4:3000, getting the Network request failed error.

**Comment by MohamedBassem** [comment]
@dodgog can you try force closing the app and trying again? Maybe once or twice?

**Comment by dodgog** [comment]
Did it like 15 times, hit the same error every time. Do I understand correctly that to force-close an app I just swipe it up out of the recent apps carousel?

**Comment by MohamedBassem** [comment]
yeah, that's what I meant. If you did it 15 times then you're probably hitting something different. Can you confirm that you can visit that address from the browser of your phone?

**Comment by dodgog** [comment]
Confirming. Can access it from safari and it doesn't even complain about security, just shows the hoarder login page as expected.

**Comment by MohamedBassem** [comment]
ok, now that's weird :) Are you using the testflight version or the prod version?
If you're using the prod version (1.3.2) can you try the testflight one (1.5.0)? (link: https://testflight.apple.com/join/QifpNxAT).

**Comment by dodgog** [comment]
Getting the same issue on 1.5.0. Shared a screenshot through developer feedback as as well, maybe it could have some useful metadata about my installation?
