### ISSUE TITLE
DISABLE_SIGNUPS not working

### ISSUE THREAD

**Issue by chanunnaki** [MohamedBassem/hoarder-app#52]
I set the .env variable to `DISABLE_SIGNUPS=true` but it didn't disable the option. 

I ran `docker compose up -s` again after saving the .env already.

**Comment by MohamedBassem** [comment]
Can you share your docker compose file?

Can you also maybe share the output of: `docker inspect hoarder-pub-web-1 | grep DISABLE_SIGNUPS` to ensure that the web container actually saw the env variable?

**Comment by chanunnaki** [comment]
Sure!

I didn’t change anything in the compose file other than the port, but I just attached for compliance.

I’m running through unRAID and for some reason that is beyond my understanding the container is called docker-pub-1, so I ran `docker inspect hoarder-pub-web-1 | grep DISABLE_SIGNUPS` and this is the output:

                "DISABLE_SIGNUPS=true”,

So it looks like the container can indeed see the variable which makes sense, because it was in the same .env file that I put in my OpenAI key.

**Comment by chanunnaki** [comment]
￼

Forgot to attach, my bad

**Comment by MohamedBassem** [comment]
hmmm, interesting. It looks right indeed. So, when you say `DISABLE_SIGNUPS` is not working, does that mean you can create an account normally?

Typically, what you'd see is that the `Signup` button is disabled similar to this screenshot:

<img width="463" alt="Screenshot 2024-03-30 at 7 11 42 PM" src="https://github.com/MohamedBassem/hoarder-app/assets/2418637/a9e82017-7acd-4307-892f-0bac03ac9f32">

**Comment by chanunnaki** [comment]
yeah, it's exactly the same:

![image](https://github.com/MohamedBassem/hoarder-app/assets/49243628/02789b16-d51f-4e57-8351-5d43ecab676a)

This screenshot was taken in another browser that I don't normally use to rule out the possibilty of the site being cached somehow.

**Comment by MohamedBassem** [comment]
Hmm, that screenshot that you shared shows the button as `disabled`. Which means that you can't really sign up.

This is what it looks like when signups is enabled:

<img width="453" alt="Screenshot 2024-03-30 at 7 45 55 PM" src="https://github.com/MohamedBassem/hoarder-app/assets/2418637/bbea838c-fd8b-4d73-985f-c6c36296d01a">

And this is what it looks like when it's disabled:

<img width="392" alt="Screenshot 2024-03-30 at 7 47 27 PM" src="https://github.com/MohamedBassem/hoarder-app/assets/2418637/4a02fdb6-fe8d-41a5-96c0-632a7b594a4a">

**Comment by chanunnaki** [comment]
Ah, I thought the signup tab is supposed to disappear completely.

My apologies, and thank you for the help.

**Comment by MohamedBassem** [comment]
hmmm, I might actually consider changing it so that it fully disappears. Makes sense.
