### ISSUE TITLE
logout redirects to localhost:3000

### ISSUE THREAD

**Issue by chanunnaki** [MohamedBassem/hoarder-app#54]
As the title says, when I logout of Hoarder, it redirects users to localhost:3000. Is there somewhere where this default redirection address can be changed?

**Comment by MohamedBassem** [comment]
This is a known issue, will fix it soon. Original issue: https://github.com/MohamedBassem/hoarder-app/issues/5

As a workaround, set `NEXTAUTH_URL` to the address of your server

**Comment by chanunnaki** [comment]
Awesome 👍

**Comment by MohamedBassem** [comment]
Closing this in favor of #5
