### ISSUE TITLE
[feature request] keyboard shortcut to focus input field

### ISSUE THREAD

**Issue by chanunnaki** [MohamedBassem/hoarder-app#58]
Sounds like the main dev is on mobile mostly, but I'm on desktop and don't like always reaching for the mouse. If there were a keyboard shortcut for focusing the text input field it would make input flow faster and more efficient.

My suggested shortcut (on Mac) would be: ⌘ + E (E for Entry) because you have ⌘ + ENTER as submission shortcut.

The flow would be as follows:

⌘ + E (focus)
⌘ + V (paste)
⌘ + ENTER (submit)

Ideally, the shortcut could be customisable for those who don't like it, but the most important part is that ⌘+E is not really a widespread standard shortcut as far as I'm aware.

Thanks for your consideration.

**Comment by MohamedBassem** [comment]
> Sounds like the main dev is on mobile mostly

Not really, I'm actually more dev on the web :)

> My suggested shortcut (on Mac) would be: ⌘ + E (E for Entry)

I love it :) Will implement it.

**Comment by chanunnaki** [comment]
Sweet :)

**Comment by MohamedBassem** [comment]
This will be included in the next release :)
