### ISSUE TITLE
Waiting for service worker 

### ISSUE THREAD

**Issue by bibinisacmohan** [MohamedBassem/hoarder-app#63]
The webpage opens up fine. However, the Chrome extension shows the following error -

![Screenshot 2024-04-01 at 3 01 43 PM](https://github.com/MohamedBassem/hoarder-app/assets/125105686/aeb606e6-5637-4a43-b618-2fea1d9c66cd)

Also, I noticed that site crawling has stopped. No preview of the webpage is available.

Following is the docker compose -

version: "3.8"
services:
  web:
    image: ghcr.io/mohamedbassem/hoarder-web:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - /volume1/docker/hoarder/data:/data
    ports:
      - 3003:3000
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      DATA_DIR: /data
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - /volume1/docker/hoarder/redis:/data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:100
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
  meilisearch:
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /volume1/docker/hoarder/meilisearch:/meili_data
  workers:
    image: ghcr.io/mohamedbassem/hoarder-workers:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - /volume1/docker/hoarder/data:/data
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      # OPENAI_API_KEY: ...
    depends_on:
      web:
        condition: service_started

**Comment by MohamedBassem** [comment]
Regarding the extension, I uploaded a development build by mistake. I now submitted a hotfix for the chrome store and waiting for google to approve. Sorry about that.

Regarding the crawler. I’ve seen one instance where the crawler gets stuck in some webpages. I have one such link, and I’m working on a fix. If you check the last crawled link in your worker logs, it’s usually that one. If you remove it from your bookmarks and restart the workers, crawling should continue. If it’s ok to share that link with me as well for debugging purposes, I’d be thankful, if not, that’s fine too.

Sorry for the inconvenience.

**Comment by MohamedBassem** [comment]
The new version is now published to the chrome store. Version 1.1.2. Chrome should auto update it for you.

**Comment by bibinisacmohan** [comment]
Thanks for the quick fix. Following is the link that was giving trouble -
https://www.tripadvisor.com/Attraction_Review-g60784-d261325-Reviews-Cuyahoga_Valley_National_Park-Brecksville_Ohio.html

I removed and resubmitted the crawl, and everything is working fine now.
