### ISSUE TITLE
'Sharp' is required to be installed...

### ISSUE THREAD

**Issue by mark-heffernan** [MohamedBassem/hoarder-app#64]
Hi there,

I'm using hoarder for the 1st time today and I'm very impressed with the web site. Thank you for your work on this so far.

While playing around with the web site today I keep seeing this error in the logs each time I upload an image or navigate to a web page with images e.g a list.  

_web-1          |  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production_

Doing some research earlier I came across these links which might help fix the issue:

- [https://github.com/lovell/sharp/issues/3877](https://github.com/lovell/sharp/issues/3877)
- [https://github.com/99lalo/nextjs-prisma-docker/tree/main?tab=readme-ov-file](https://github.com/99lalo/nextjs-prisma-docker/tree/main?tab=readme-ov-file)

The dev states that sharp needs to be set to version 0.32.6. Might be useful.  

Thanks 👍

**Comment by MohamedBassem** [comment]
Hello, thanks for your words and thanks also for taking the time to dig into the issue. Your research is correct, I've already fixed this issue in https://github.com/MohamedBassem/hoarder-app/commit/48169a03b177a2d095c235df21c03ef59168e8ab and it'll be included in the next release! :)

**Comment by MohamedBassem** [comment]
Closing this as fixed for now.
