### ISSUE TITLE
cannot change the web app listening port from 3000

### ISSUE THREAD

**Issue by tdereus** [MohamedBassem/hoarder-app#67]
I have mutliple docker containers running on my host and some other use port 3000.  Can you include an environement variable so you can change the listening port of the hoader web app?

**Comment by MohamedBassem** [comment]
You don’t need an env variable to do that. Just map the port 3000 on the container to some other port on the host. If you’re using docker compose, change the line that says ‘3000:3000’ to ‘3010:3000’ for example.
