### ISSUE TITLE
Please allow for the ability to change the tagging language when using OpenAI for automatic tagging.

### ISSUE THREAD

**Issue by COOHU-Kr** [MohamedBassem/hoarder-app#68]
"Please consider supporting languages other than English to accommodate users who speak different languages."

**Comment by MohamedBassem** [comment]
This is a great idea and shouldn't be too hard.

**Comment by MohamedBassem** [comment]
This will be available in the next release. Thanks for the suggestion!

**Comment by z-hhh** [comment]
> This will be available in the next release. Thanks for the suggestion!

Very excited about this feature ❤️.

**Comment by MohamedBassem** [comment]
@z-hhh This was already released in three v11 release :)
