### ISSUE TITLE
[Feature Request] Allow adding bookmarks while inside a list

### ISSUE THREAD

**Issue by silentdefault** [MohamedBassem/hoarder-app#69]
First: I really like the app, it's (almost) all i want to reemplace raindrop.
Please add:
- Nested List.
- The option to add links/notes when i'm "inside" a list
- Favicons

**Comment by MohamedBassem** [comment]
Hi! I'm glad you're liking it!
- Nested lists are tracked in https://github.com/MohamedBassem/hoarder-app/issues/62
- Adding items when inside the list makes sense. I'll track it in this issue.
- What do you mean by favicons? I'm currently already storing the favicons of the links I'm crawling but I'm not showing them anywhere in the UI. Any suggestion how you want to see them?

**Comment by MohamedBassem** [comment]
The editor card will now be available in list/tag view pages, archive and favourite pages :) This will be available in the next release! Thanks for the suggestion!
