### ISSUE TITLE
Allow setting tags from Firefox extension

### ISSUE THREAD

**Issue by bob912** [MohamedBassem/hoarder-app#71]
It would be awesome to be able to assign tags to articles when creating from the Firefox extension. This would save having to go into Hoarder separately to set tags.

Otherwise already working great for my bookmarking!

**Comment by MohamedBassem** [comment]
I'm surprised that this took too long to get requested. It'll definitely be implemented :) Both adding tags and adding to lists.

**Comment by hunter-commits** [comment]
I have a suggestion for this feature.

It would be great if there was a quick select option for the most commonly used tags and lists. This would be quicker than having to search or use a drop down menu every time we are saving a website.

Here's a simple mockup to show what I'm talking about:
![mockup](https://github.com/MohamedBassem/hoarder-app/assets/141588416/3978b12c-35cc-4054-9bd9-e3febe348c8a)

**Comment by MohamedBassem** [comment]
This is now completed in https://github.com/MohamedBassem/hoarder-app/commit/77b1aba5acc66dfaeb02b08d60d88442336026a6. It's released as version `1.2.0` which is available now in firefox and pending google's review for chrome (give it a day or so).

**Comment by MohamedBassem** [comment]
Screenshot:

<img width="378" alt="Screenshot 2024-04-23 at 2 17 30 PM" src="https://github.com/MohamedBassem/hoarder-app/assets/2418637/b791a567-b307-4e0f-b54a-2305020a3ed1">

**Comment by perdakovich** [comment]
how can i use firefox's native bookmark menu to tag?
some kind of firefox/karakeep bookmarks auto-sync ? that would be really good, because i like the native interface and i don't even need the extension really
