### ISSUE TITLE
Why chrome error?

### ISSUE THREAD

**Issue by jiangaq** [MohamedBassem/hoarder-app#72]
When  doing `docker compose up -d`,it returns: 

```
chrome Error                                                                                                                                         
Error response from daemon: Head "https://gcr.io/v2/zenika-hub/alpine-chrome/manifests/123":
```

**Comment by MohamedBassem** [comment]
Oh, that's a bug. Can you in the docker compose file replace `gcr.io/zenika-hub/alpine-chrome:123` with `zenika-hub/alpine-chrome:123`. Let me know if this fixes it. I'll send a quick fix now.

**Comment by MohamedBassem** [comment]
Actually, the GCR link should work. But you can try the suggestion that I mentioned if it didn't.

**Comment by jiangaq** [comment]
> Oh, that's a bug. Can you in the docker compose file replace `gcr.io/zenika-hub/alpine-chrome:123` with `zenika/alpine-chrome:123`. Let me know if this fixes it. I'll send a quick fix now.

it returns:
`Error response from daemon: pull access denied for zenika-hub/alpine-chrome, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

**Comment by jiangaq** [comment]
It works now.

By the way, is there possible to use proxy openai base url instead?

**Comment by jiangaq** [comment]
I found some pages "Failed to fetch link content ..." Why it got error? Are they waiting to fetch in background?

**Comment by MohamedBassem** [comment]
Checking the logs of the `workers` container should tell you why they failed. You can retry them by clicking the `refresh` button in the bookmark option menu.

**Comment by MohamedBassem** [comment]
Please reopen if you still need help :)
