### ISSUE TITLE
Tag numbers don't seem to reflect the actual times they are used?

### ISSUE THREAD

**Issue by ovizii** [MohamedBassem/hoarder-app#78]
I just upgraded to 0.11.0 – definitely not a caching issue, I tried different browsers.

![image](https://github.com/MohamedBassem/hoarder-app/assets/837902/893508f3-fc7e-4f1e-a1a3-5291feb7ada2)

But clicking a tag shows more than 1 result:

![image](https://github.com/MohamedBassem/hoarder-app/assets/837902/09652d91-01e0-4ed5-8823-c87d595a13c1)

**Comment by MohamedBassem** [comment]
Thanks for the report. This is now hotfixed in `v0.11.1`
