### ISSUE TITLE
Disable new users sign-up

### ISSUE THREAD

**Issue by AlexMV12** [MohamedBassem/hoarder-app#8]
Hi Mohamed,

This is indeed a very interesting app!

I am suggesting a feature: **disable new users sign-up**

## Usecase
After the app is deployed and exposed to internet, it is possible to sign-up. However, it would be nice to prevent other people from signing up to one's instance.

Thanks for your work.

**Comment by MohamedBassem** [comment]
Hi, this makes a lot of sense that I already have it :) I just forgot to document it.

Add `DISABLE_SIGNUPS=true` to your `.env` files and signups will be disabled in both the backend and the frontend :) Will use this issue to fix the documentation!
