### ISSUE TITLE
Feature: add some tag sorting options

### ISSUE THREAD

**Issue by ovizii** [MohamedBassem/hoarder-app#80]
Currently, they seem to be sorted by the number of tagged bookmarks. I prefer them sorted alphabetically. 

Optionally, a tag cloud sounds great where the size or the intensity of the colour indicates the most used tags?

**Comment by kamtschatka** [comment]
Sorting by name has been added with #154.
Additionally the bookmarks are now also sorted alphabetically if they have the same amount of of bookmarks they are assigned to.

**Comment by MohamedBassem** [comment]
Thanks @kamtschatka!
