### ISSUE TITLE
Bug: New note with ':' causes failure

### ISSUE THREAD

**Issue by derekslenk** [MohamedBassem/hoarder-app#86]
Noticed this when pasting a key:value pair into a note. It appears that anything with a `:` cause the note to try and use it as a URL, and when it finally gives up (`Crawling job failed: {}`) it just shows: `Failed to fetch link content ...`

When trying to open the note, it tries to browse to key:value in my browser.

**Comment by MohamedBassem** [comment]
Oh that's a good catch. I think I'll enforce that URLs must have a protocol in them (e.g. https:// or http://) for them to be considered as URLs I guess.

**Comment by derekslenk** [comment]
I wasn't trying to paste a URL, that is the problem. It was a note with JUST a `key:value` entry.

I have been doing some testing, and it only occurs if the `:` is directly after the first work (or maybe before the first space?).

For example, `look: broken` breaks it.

But if I do `look here: not broken`, it works fine.

Hope that clears it up

**Comment by MohamedBassem** [comment]
Yeah, I managed to repro and already have a fix that will be available in the next release. Thanks for the report!
