### ISSUE TITLE
YouTube links don't render thumbnails or descriptions and don't fetch the link content for the viewer.

### ISSUE THREAD

**Issue by nothing2obvi** [MohamedBassem/hoarder-app#87]
As seen below. One link is to an English music video and one link is to a Japanese music video (and description).

![Screen Shot 2024-04-07 at 12 24 37 PM](https://github.com/MohamedBassem/hoarder-app/assets/85228035/0b09ee2f-0f46-4513-9fdf-d3632f76eae1)

![Screen Shot 2024-04-07 at 12 24 48 PM](https://github.com/MohamedBassem/hoarder-app/assets/85228035/a7d2bc2c-828d-4d11-af10-511c736562e6)

**Comment by MohamedBassem** [comment]
Hi, this seems like the crawler is actually not working. Can you share the logs of the `workers` container?

**Comment by nothing2obvi** [comment]
Here they are. I don't think they'll be helpful. Do I need to change the type of logs, and how would I do that?

```
04/10/2024
01:49:14 PM
2024-04-10T20:49:14.735Z info: Successfully resolved IP address, new address: http://172.31.0.5:9222/
04/10/2024
01:50:19 PM
2024-04-10T20:50:19.086Z info: [Crawler][2] Will crawl "https://www.youtube.com/watch?v=lo4KMGiy--Y" for link with id "r0qcnujiw78s5doz082upatu"
04/10/2024
01:50:19 PM
2024-04-10T20:50:19.201Z info: [search][2] Completed successfully
04/10/2024
01:50:29 PM
2024-04-10T20:50:29.484Z error: [Crawler][2] Crawling job failed: {"name":"TimeoutError"}
```

**Comment by MohamedBassem** [comment]
Is this still happening after the latest release where I increased the navigation timeout?

**Comment by MohamedBassem** [comment]
Please re-open if this is still an issue.
