### ISSUE TITLE
[Feature request] Keep last list selected when adding to list

### ISSUE THREAD

**Issue by bitegw** [MohamedBassem/hoarder-app#90]
As #84 and #69 mention, adding items to lists is very tedious, I second these suggestions.

I've been manually going through my old bookmarks and adding the still useful ones to hoarder, and I often want to add multiple of them directly to a list, but there's no way to do so. I have to add them as items, then I go through each item and click add to list, and then I have to click again and select the same list again many many times. The other feature requests are better but until they are implemented at least remember the last list that was added to.

**Comment by MohamedBassem** [comment]
Hey, thanks for the suggestion! I agree with you that migrating right now is tedious. I'm not sure however that remembering the last list is the best UX because not everyone is mass importing (it's not the default mode of operation). If #69 solves your issue, I think I can prioritize that one instead :)

**Comment by bitegw** [comment]
That works for me, but I do think last list selected is still better default behavior since currently there is no list selected (not even first), so you always have to click the dropdown to pick a list. This would save the user two clicks at least some of the time, and not just when importing. I agree that it's low priority though.

**Comment by MohamedBassem** [comment]
@bitegw I hope with https://github.com/MohamedBassem/hoarder-app/issues/69 this is no longer needed? Feel free to reopen if you still have strong opinions about it :D
