### ISSUE TITLE
[Feature Request] Add a token cutoff

### ISSUE THREAD

**Issue by Reledia** [MohamedBassem/hoarder-app#94]
Hello. Sometimes, some pages I save contains essays or stories that can span aboce 20k+ tokens. This does not only used much more credits/money when doing a request, but it consumes a lot of time (from 4s to >50s) and the prompt get lost in the way.

Would it be possible to add an env variable so we can set the max number of tokens to send in a single request?

**Comment by MohamedBassem** [comment]
Hi, there's already a hardcoded token cutoff of 1500 tokens (to fit in the context window of some models). But making this configurable makes a ton of sense :) Should be easy to implement and include in the next release. Thanks for the suggestion!

**Comment by Reledia** [comment]
I'm happy to hear this was already implemented, but I observe a different thing in my logs

![Screenshot_20240411_125943_Vivaldi.jpg](https://github.com/MohamedBassem/hoarder-app/assets/82183718/92e1c732-39ec-4061-a27d-25b016f1ebf3)

My version of hoarder should be the latest available

**Comment by MohamedBassem** [comment]
Oh wow, that's a lot of tokens. Hmmm, I have a guess. I'm currently approximating `tokens` to `words`. So technically speaking I'm truncating the content to 1500 words not tokens. Maybe that's where the difference is coming from? Do you have a link that you are willing to share for me to debug this? Thanks!

**Comment by Reledia** [comment]
I don't wanna share the actual link because it's very explicit, but it was a chapter of a fanfiction from AO3, so very heavy on words

**Comment by MohamedBassem** [comment]
Turned out, I had a bug in the content truncating logic. Sending a fix now.

**Comment by Reledia** [comment]
By looking at the commit, was the truncate function sending words only after the 1500th one?

**Comment by MohamedBassem** [comment]
Yeah, noob mistake :)

**Comment by Reledia** [comment]
Dont worry, it happens to everyone :)
But maybe in the next release it would be better to inform users to re-process all previous bookmarks?

**Comment by Reledia** [comment]
Seems like the best solution. Thanks for the time
